version: '3'
services:
    web:
        image: ng_image
        container_name: ng_lunes
        build: .
        ports: 
            - "4200:4200"
            - "49153:49153"
        volumes:
            - "/app/node_modules" 
            - ".:/app"
            
